### ISSUE TITLE
[Design] The last frame of fish puffing

### ISSUE THREAD

**Issue by itsumu** [Hesitater/Puffer-Fish#1]

**Comment by itsumu** [comment]
Finished.[https://github.com/Hesitater/Puffer-Fish/commit/30cd493eee89dc7364de4dbd88c9864cb0c3ec71](https://github.com/Hesitater/Puffer-Fish/commit/30cd493eee89dc7364de4dbd88c9864cb0c3ec71)

**Comment by Hesitater** [comment]
Finished.[https://github.com/Hesitater/Puffer-Fish/commit/30cd493eee89dc7364de4dbd88c9864cb0c3ec71](https://github.com/Hesitater/Puffer-Fish/commit/30cd493eee89dc7364de4dbd88c9864cb0c3ec71)
