### ISSUE TITLE
Fish fly away when colliding with multiple bubbles

### ISSUE THREAD

**Issue by itsumu** [Hesitater/Puffer-Fish#12]

**Comment by Hesitater** [comment]
[Finished](055ec51be3c7d265aa33c5f82b6aabb7ddc77f5e)

**Comment by itsumu** [comment]
Fish can no longer collide with two bubbles at the same time. [https://github.com/Hesitater/Puffer-Fish/commit/e7718928e8e4a0e5f9130004696c670d137375a9](https://github.com/Hesitater/Puffer-Fish/commit/e7718928e8e4a0e5f9130004696c670d137375a9)
